/*
 * Copyright 2025 Silkwood Software Pty. Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Component for displaying and managing a table of files.
   * 
   * This docstring was generated by GPT-4o in Aider.
 */
import { Component, OnInit, ViewChild, ElementRef, AfterViewInit, HostListener, Input, OnDestroy } from '@angular/core';
import { GenericTableService, TableType } from '../../shared/services/generic-table.service';
import { TableStateService } from '../../shared/services/table-state.service';
import { TableActionsService } from '../../shared/services/table-actions.service';
import { TableConfigService } from '../../shared/services/table-config.service';
import { FileReadingService } from './file-reading.service';
import { FileDownloadService } from '../file-download/file-download.service';
import { ActivatedRoute } from '@angular/router';
import { SelectedIdsService } from '../../shared/services/selected-ids.service';
import { MessageLabelService } from '../../shared/services/message-label.service';
import { Subscription } from 'rxjs';
import { ChangeDetectorRef } from '@angular/core';
import { TableSelectionExtensionService } from '../../shared/services/table-selection-extension.service';


interface FileData {
  [key: string]: any;
}

@Component({
  selector: 'app-files-table',
  templateUrl: './files-table.component.html',
  styleUrls: ['../../shared/stylesheets/tables.scss', '../../shared/stylesheets/messages.scss']
})
export class FilesTableComponent implements OnInit, AfterViewInit, OnDestroy {
  @Input() tableHeading: string = '';
  private isDragging: boolean = false;
  private dragStartPosition: { x: number, y: number } | null = null;
  fileData: FileData[] = [];
  columns: string[] = [];
  message: string = '';
  transactionStatus: string = '';
  numberOfRows: string = '';
  numberOfFiles: string = '';
  selectedRows: FileData[] = [];
  selectedIds: (string | number)[] = [];
  messageItems: { label: string, value: string }[] = [];
  lastSelectedIndex: number = -1;
  private recordUpdatedSubscription: Subscription | undefined;
  tooltips: { [key: string]: string } = {};
  columnMapping: {[key: string]: string} = {};

  @ViewChild('tableContainer') tableContainer!: ElementRef;  
  
  readonly tableType: TableType = {
    name: 'Files',
    endpoint: 'file/list-all-files',
    idType: 'bigint',
    dataField: 'fileData'
  };

  constructor(
    private genericTableService: GenericTableService<FileData>,
    private tableStateService: TableStateService,
    private tableActionsService: TableActionsService,
    private fileDownloadService: FileDownloadService,
    private tableConfigService: TableConfigService,
    private selectedIdsService: SelectedIdsService,
    private messageLabelService: MessageLabelService,
    private cdr: ChangeDetectorRef,
    private tableSelectionExtensionService: TableSelectionExtensionService
    ) { }

  /**
   * Initializes the component by fetching all files metadata.
   *
   * Preconditions:
   *   - The component has been created.
   *
   * Side effects:
   *   - Updates the filesMetadata property with the fetched data.
   *
   * Exceptions:
   *   - None.
   * 
   * This docstring was generated by GPT-4o in Aider.
   */
  getSortState(tableName: string): { column: string, direction: 'asc' | 'desc' } {
    return this.tableStateService.getSortState(tableName);
  }  
  ngOnInit(): void {
    // Fetch all files metadata when the component initializes
    this.fetchAllFilesData();
    this.tableStateService.tableState$.subscribe(state => {
      if (state[this.tableType.name]) {
        this.selectedRows = state[this.tableType.name].selectedRows;
        this.selectedIds = state[this.tableType.name].selectedIds;  
        this.tableHeading = 'All Files';      
        this.applySortState();
        this.applyColumnWidths();        
      }
    });
    this.recordUpdatedSubscription = this.tableStateService.recordUpdated$.subscribe(
      (tableName: string) => {
        if (tableName === this.tableType.name) {
          this.refreshTable();
        }
      }
    );
  }

  refreshTable(): void {
    this.fetchAllFilesData();
  }

  ngOnDestroy(): void {
    if (this.recordUpdatedSubscription) {
      this.recordUpdatedSubscription.unsubscribe();
    }
  }
  ngAfterViewInit(): void {
    this.initializeColumnWidths();
  }

  initializeColumnWidths(): void {
    if (this.tableContainer && this.tableContainer.nativeElement) {
    const tableElement = this.tableContainer.nativeElement.querySelector('table');
    if (tableElement) {
      const headerCells = tableElement.querySelectorAll('th');
      const columnWidths = Array.from(headerCells).map(cell => (cell as HTMLElement).offsetWidth);
      this.tableStateService.setColumnWidths(this.tableType.name, columnWidths);
    }
   }
  }  
  /**
   * Fetches metadata for all files and updates the filesMetadata property.
   *
   * Preconditions:
   *   - The fileReadingService is available and properly configured.
   *
   * Side effects:
   *   - Updates the filesMetadata property with the fetched data.
   *   - Logs errors to the console if the request fails.
   *
   * Exceptions:
   *   - None.
   * 
   * This docstring was generated by GPT-4o in Aider.
   */
  fetchAllFilesData(): void {
    this.genericTableService.getTableData(this.tableType).subscribe({
      next: (data: any) => {
        if (data && data.data) {
          this.fileData = data.data;
          if (this.fileData.length > 0) {
            this.columns = Object.keys(this.fileData[0]);
          }
          this.message = data.transactionMessage || '';
          this.transactionStatus = data.transactionStatus || '';
          this.numberOfFiles = data.numberOfFiles || '';
          this.tableStateService.setTableData(this.tableType.name, this.fileData);
          this.initializeColumnWidths();      
          this.updateMessageItems(data);   
          this.tooltips = data.tooltips || {}; 
          this.columnMapping = data.columnMapping || {};
          console.log('Tooltips received:', this.tooltips);
          console.log('Column mapping:', this.columnMapping);          
        } else {
          console.error('Unexpected data structure:', data);
        }
      },
      error: (error) => {
        // The following line logs the detailed error object to the console
        console.error('Error fetching files data:', error);
      }
    });
  }
  private updateMessageItems(data: any): void {
    this.messageItems = [
      { label: this.messageLabelService.getLabel('transactionMessage'), value: data.transactionMessage || '' },
      { label: this.messageLabelService.getLabel('transactionStatus'), value: data.transactionStatus || '' },
      { label: this.messageLabelService.getLabel('numberOfFiles'), value: data.numberOfFiles?.toString() || '' }
    ];
  }

  onRowSelect(row: FileData): void {
    this.selectedRows = [row];
    this.selectedIds = [this.getRowId(row)];
    this.tableStateService.setSelectedRows(this.tableType.name, this.selectedRows);
    this.selectedIdsService.setSelectedFileIds([Number(this.getRowId(row))]);
    this.selectedIdsService.setSelectedFilenames([row['Filename']]);
    
    // Process ID/Name pairs without changing existing functionality
    // Use the correct table name from read-routes.csv
    this.tableSelectionExtensionService.processSelectedRows('list-all-files', [row]);
  }

  onRowMultiSelect(event: MouseEvent, row: FileData): void {
    if (!this.isDragging) {
      const index = this.fileData.indexOf(row);
      if (event.ctrlKey || event.metaKey) {
        const selectedIndex = this.selectedRows.indexOf(row);
        if (selectedIndex > -1) {
          this.selectedRows.splice(selectedIndex, 1);
          this.selectedIds.splice(selectedIndex, 1);
        } else {
          this.selectedRows.push(row);
          this.selectedIds.push(this.getRowId(row));
        }
        this.lastSelectedIndex = index;
      } else if (event.shiftKey && this.lastSelectedIndex > -1) {
        const start = Math.min(this.lastSelectedIndex, index);
        const end = Math.max(this.lastSelectedIndex, index);
        this.selectedRows = this.fileData.slice(start, end + 1);
        this.selectedIds = this.selectedRows.map(selectedRow => this.getRowId(selectedRow));
      } else {
        this.selectedRows = [row];
        this.selectedIds = [this.getRowId(row)];
        this.lastSelectedIndex = index;
      }
      
      this.tableStateService.setSelectedRows(this.tableType.name, this.selectedRows);
      this.selectedIdsService.setSelectedFileIds(this.selectedIds.map(id => Number(id)));
      this.selectedIdsService.setSelectedFilenames(this.selectedRows.map(row => row['Filename']));
      
      // Process ID/Name pairs without changing existing functionality
      // Use the correct table name from read-routes.csv
      this.tableSelectionExtensionService.processSelectedRows('list-all-files', this.selectedRows);
    }
  }

  private getRowId(row: FileData): number {
    return row['File ID'];
  }
    
  
  @HostListener('mousedown', ['$event'])
  onMouseDown(event: MouseEvent): void {
    this.isDragging = false;
    this.dragStartPosition = { x: event.clientX, y: event.clientY };
  }

  @HostListener('mousemove', ['$event'])
  onMouseMove(event: MouseEvent): void {
    if (this.dragStartPosition) {
      const dragDistance = Math.sqrt(
        Math.pow(event.clientX - this.dragStartPosition.x, 2) +
        Math.pow(event.clientY - this.dragStartPosition.y, 2)
      );
      if (dragDistance > 5) {
        this.isDragging = true;
      }
    }
  }

  @HostListener('mouseup', ['$event'])
  onMouseUp(event: MouseEvent): void {
    this.isDragging = false;
    this.dragStartPosition = null;
  }
  onColumnSelect(column: string): void {
    const currentSortState = this.tableStateService.getSortState(this.tableType.name); 
    let newDirection: 'asc' | 'desc' = 'asc';
    if (currentSortState.column === column) {
      // If the same column is clicked, toggle the sort direction
      newDirection = currentSortState.direction === 'asc' ? 'desc' : 'asc';
    }    
    this.tableActionsService.sortTable(this.tableType.name, column, newDirection);
    this.applySortState();
  }

  applySortState(): void {
    const sortState = this.tableStateService.getSortState(this.tableType.name);
    if (sortState.column) {
      this.fileData = this.genericTableService.sortTableData(this.fileData, sortState.column, sortState.direction);
    }
  }
  
  
  /**
   * Initiates the download of a file by its ID and filename.
   *
   * Args:
   *   fileId (number): The ID of the file to download.
   *   filename (string): The name of the file to download.
   *
   * Preconditions:
   *   - fileId is a valid number.
   *   - filename is a non-empty string.
   *
   * Side effects:
   *   - Initiates a file download in the browser.
   *
   * Exceptions:
   *   - None.
   * 
   * This docstring was generated by GPT-4o in Aider.
   */
  downloadFile(fileId: number): void {
    this.fileDownloadService.downloadFile(fileId); 
  }

  onColumnResize(event: MouseEvent, columnIndex: number): void {
    event.preventDefault();
    if (this.tableContainer && this.tableContainer.nativeElement) {    
     const headerRow = this.tableContainer.nativeElement.querySelector('tr');
     const th = headerRow.children[columnIndex] as HTMLElement;
     const startX = event.pageX;
     const startWidth = th.offsetWidth;

     const onMouseMove = (moveEvent: MouseEvent) => {
      const deltaX = moveEvent.pageX - startX;
      const newWidth = Math.max(50, startWidth + deltaX);
      th.style.width = `${newWidth}px`;
    };

    const onMouseUp = () => {
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
      this.saveColumnWidths();
    };

    document.addEventListener('mousemove', onMouseMove);
    document.addEventListener('mouseup', onMouseUp);
   }
  }
 
 applyColumnWidths(): void {
  const columnWidths = this.tableStateService.getColumnWidths(this.tableType.name);
  if (this.tableContainer && this.tableContainer.nativeElement) {  
  const tableElement = this.tableContainer.nativeElement.querySelector('table');
  if (tableElement) {
    columnWidths.forEach((width, index) => {
      const thElement = tableElement.querySelector(`th:nth-child(${index + 1})`);
      if (thElement) {
        thElement.style.width = `${width}px`;
      }
    });
  }
 }
}
saveColumnWidths(): void {
  if (this.tableContainer && this.tableContainer.nativeElement) {  
  const headerCells = this.tableContainer.nativeElement.querySelectorAll('th');
  const columnWidths = Array.from(headerCells).map(cell => (cell as HTMLElement).offsetWidth);
  this.tableStateService.setColumnWidths(this.tableType.name, columnWidths);
}
}

getTooltip(column: string): string {
  const fullKey = this.columnMapping[column];
  return fullKey ? (this.tooltips[fullKey] || '') : '';
}

}
