/*
 * Copyright 2025 Silkwood Software Pty. Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Retrieve the data for all files
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../../../src/environments/environment';

/**
 * Service for reading file data from the backend.
   * 
   * This docstring was generated by GPT-4o in Aider.
 */
@Injectable({
  providedIn: 'root'
})
export class FileReadingService {  
  private readonly apiUrl = environment.dotNetBaseUrl; 

  constructor(private http: HttpClient) { }

  /**
   * Retrieves metadata for all files from the backend.
   *
   * Preconditions:
   *   - The HttpClient is available and properly configured.
   *
   * Side effects:
   *   - Makes an HTTP GET request to the backend.
   *
   * Exceptions:
   *   - None.
   *
   * Returns:
   *   Observable<any>: An observable containing the metadata for all files.
   *   guarantees: The observable will emit the file metadata or an error.
   * 
   * This docstring was generated by GPT-4o in Aider.
   */
  getAllFilesData(formId?: number | null): Observable<any> {
    const url = formId !== undefined && formId !== null
    ? `${this.apiUrl}/file/list-all-files?formId=${formId}`
    : `${this.apiUrl}/file/list-all-files`;
    return this.http.get(url);
  }

 
}
